
import {
  LayoutDashboard,
  Wallet,
  Landmark,
  TrendingUp,
  LineChart,
  ChevronDown,
  ChevronRight,
  Plus,
  MoreHorizontal,
  ArrowDownCircle,
  ArrowUpCircle,
  FileText,
  PiggyBank,
  PieChart,
  Target,
  FileJson,
  UploadCloud,
  BrainCircuit,
  Settings,
  Trash2,
  ArrowLeftRight,
  AlertTriangle,
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Expenses: Wallet,
  Debts: Landmark,
  Income: TrendingUp,
  Investments: LineChart,
  Purchases: BrainCircuit,
  ChevronDown: ChevronDown,
  ChevronRight: ChevronRight,
  Plus: Plus,
  More: MoreHorizontal,
  Expense: ArrowDownCircle,
  IncomeIcon: ArrowUpCircle,
  CSV: FileText,
  Savings: PiggyBank,
  Allocation: PieChart,
  Goal: Target,
  JSON: FileJson,
  Upload: UploadCloud,
  Insights: BrainCircuit,
  Settings: Settings,
  Trash: Trash2,
  Sync: ArrowLeftRight,
  Warning: AlertTriangle,
};